# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build websitino (windows)

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        dc: [ldc-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Set version info for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $VERSION = "${{ github.ref }}".Replace('refs/tags/', '')
        echo "enum WEBSITINO_VERSION = ""$VERSION"";" | Out-File -Append -Encoding utf8 source/app.d

    - name: 'Build & Test'
      run: |
        dub build --compiler=ldc2 --build=release --config=windows-static

    - name: Smoke test
      shell: bash
      run: tests/smoke.sh ./websitino.exe --no-https

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: websitino.exe
        path: websitino.exe
